<a href="https://colab.research.google.com/github/Nithin7791/Pytorch_GColab_understanding/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)

1.12.0+cu113


Introduction to Tensors

Creating tensors

In [6]:
#scalar
scalar = torch.tensor(7)

In [7]:
scalar.ndim

0

In [8]:
scalar.item()

7

In [9]:
 #Vector
vector = torch.tensor([7, 7])
vector
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
#Matrix
matrix = torch.tensor([[1, 2, 3], 
                       [4, 5, 6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
matrix.ndim

2

In [13]:
matrix.shape

torch.Size([2, 3])

In [14]:
matrix[0]

tensor([1, 2, 3])

In [15]:
#Tensor 1 with channel (Pytorch is CHW format)
tensor1 = torch.tensor([[[1, 2, 3, 4],
                         [4, 5, 6, 5]],
                        [[7, 8, 9, 1],
                         [1, 2, 3, 4]]])
tensor1.ndim

3

In [16]:
tensor1.shape

torch.Size([2, 2, 4])

In [17]:
tensor1.size()

torch.Size([2, 2, 4])

In [18]:
tensor1[0]

tensor([[1, 2, 3, 4],
        [4, 5, 6, 5]])

In [26]:
#Tensor 2 with channel (Pytorch is CHW format)
tensor2 = torch.tensor([[[[1, 2, 3, 4],
                         [4, 5, 6, 5]],
                        [[7, 8, 9, 1],
                         [1, 2, 3, 4]]],
                       [[[1, 2, 3, 4],
                         [4, 5, 6, 5]],
                        [[7, 8, 9, 1],
                         [1, 2, 3, 4]]],
                        [[[1, 2, 3, 4],
                         [4, 5, 6, 5]],
                        [[7, 8, 9, 1],
                         [1, 2, 3, 4]]]])

In [27]:
tensor2.ndim

4

In [28]:
tensor2.shape

torch.Size([3, 2, 2, 4])

### random tensors

In [32]:
# Random tensors
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3131, 0.5646, 0.5550, 0.5628],
        [0.0148, 0.3688, 0.7781, 0.8468],
        [0.5565, 0.0558, 0.9871, 0.7292]])

In [33]:
random_tensor.shape

torch.Size([3, 4])

In [36]:
random_tensor = torch.rand(3, 3, 4)
random_tensor

tensor([[[0.1054, 0.5629, 0.5052, 0.4475],
         [0.0631, 0.2510, 0.0635, 0.0685],
         [0.9880, 0.1297, 0.7189, 0.7070]],

        [[0.7136, 0.4872, 0.5224, 0.0688],
         [0.8843, 0.3879, 0.1335, 0.3406],
         [0.7838, 0.8989, 0.7054, 0.9815]],

        [[0.6035, 0.2531, 0.9521, 0.1393],
         [0.4790, 0.7935, 0.1644, 0.4804],
         [0.3939, 0.4672, 0.8874, 0.0013]]])

In [37]:
random_tensor.shape

torch.Size([3, 3, 4])

In [39]:
# CHW
random_tensor2 = torch.rand(size=(3, 3, 4))
random_tensor2

tensor([[[0.9757, 0.4931, 0.1416, 0.4416],
         [0.9030, 0.6127, 0.8875, 0.0730],
         [0.6985, 0.8598, 0.7656, 0.6969]],

        [[0.6088, 0.0226, 0.3275, 0.9754],
         [0.5832, 0.8411, 0.3456, 0.0560],
         [0.5241, 0.7538, 0.2459, 0.6385]],

        [[0.5473, 0.1745, 0.2180, 0.1553],
         [0.4002, 0.2008, 0.6625, 0.4408],
         [0.1624, 0.9263, 0.9926, 0.5899]]])

In [40]:
random_tensor2.dtype

torch.float32