<a href="https://colab.research.google.com/github/Nithin7791/Pytorch_GColab_understanding/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)

1.12.0+cu113


Introduction to Tensors

Creating tensors

In [3]:
#scalar
scalar = torch.tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
 #Vector
vector = torch.tensor([7, 7])
vector
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#Matrix
matrix = torch.tensor([[1, 2, 3], 
                       [4, 5, 6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 3])

In [11]:
matrix[0]

tensor([1, 2, 3])

In [16]:
#Tensor 2 with channel (Pytorch is CHW format)
tensor1 = torch.tensor([[[1, 2, 3, 4],
                         [4, 5, 6, 5]],
                        [[7, 8, 9, 1],
                         [1, 2, 3, 4]]])
tensor1.ndim

3

In [17]:
tensor1.shape

torch.Size([2, 2, 4])

In [19]:
tensor1.size()

torch.Size([2, 2, 4])

In [20]:
tensor1[0]

tensor([[1, 2, 3, 4],
        [4, 5, 6, 5]])